# Diabetes - Multi-Layer Perceptron (MLP) with Keras

### Imports and Setup

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd

diabetes_dataframe_training = pd.read_csv('..\\diabetes_dataset(s)\\diabetes_binary_5050split_health_indicators_BRFSS2015.csv')

X_train = diabetes_dataframe_training.drop('Diabetes_binary', axis=1)
y_train = diabetes_dataframe_training['Diabetes_binary']

diabetes_dataframe_training.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

In [31]:
diabetes_dataframe_testing = pd.read_csv('..\\diabetes_dataset(s)\\diabetes_binary_5050split_health_indicators_BRFSS2015.csv')

X_test = diabetes_dataframe_testing.drop('Diabetes_binary', axis=1)
y_test = diabetes_dataframe_testing['Diabetes_binary']

diabetes_dataframe_testing.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

In [32]:
# Check for number of unique values in each column (for categorical variables)
diabetes_dataframe_training.nunique()

Diabetes_binary          2
HighBP                   2
HighChol                 2
CholCheck                2
BMI                     80
Smoker                   2
Stroke                   2
HeartDiseaseorAttack     2
PhysActivity             2
Fruits                   2
Veggies                  2
HvyAlcoholConsump        2
AnyHealthcare            2
NoDocbcCost              2
GenHlth                  5
MentHlth                31
PhysHlth                31
DiffWalk                 2
Sex                      2
Age                     13
Education                6
Income                   8
dtype: int64

### Data Preprocessing

Seems the dataset will require encoding, as almost all features are categorical. We will use OneHotEncoder for the nominal features and OrdinalEncoder for the ordinal features.

In [33]:
# make prerocessor
preprocessor = ColumnTransformer(transformers=[
    ('ordinal', OrdinalEncoder(), ['Income', 'Education', 'Age', 'GenHlth',]),
    ('nominal', OneHotEncoder(), ['Sex','DiffWalk', 'NoDocbcCost', 'AnyHealthcare', 'HvyAlcoholConsump', 'Veggies', 'Fruits', 'PhysActivity', 
                                  'HeartDiseaseorAttack', 'Stroke', 'Smoker', 'CholCheck', 'HighChol', 'HighBP']),
    ('numerical', StandardScaler(), ['PhysHlth', 'MentHlth', 'BMI'])
])

# process data
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.fit_transform(X_test)

# check the shape of the processed data
X_train_processed.shape, X_test_processed.shape

((70692, 35), (70692, 35))

### Build the Multi-Layer Perceptron (MLP) Model

With one layer and 100 nodes

In [34]:
processing = layers.Normalization(axis=-1)
processing.adapt(X_train_processed)

In [ ]:
# Implement MLP with one hidden layer with 100 nodes and the relu activation function 
# Compile the model with loss='mean_absolute_error' and optimizer=tf.keras.optimizers.Adam(0.001)
# Fit the model using validation_split=0.2, verbose=0 and epochs=100

# convert to tensors due to compatibility issue
X_train_processed = tf.convert_to_tensor(X_train_processed, dtype=tf.float32)
X_test_processed = tf.convert_to_tensor(X_test_processed, dtype=tf.float32)
y_train = tf.convert_to_tensor(y_train, dtype=tf.float32)
y_test = tf.convert_to_tensor(y_test, dtype=tf.float32)


one_layer_model = keras.Sequential([
    layers.Dense(100, activation='relu'),
    layers.Dense(1)
])
one_layer_model.compile(loss='mean_absolute_error', optimizer=tf.keras.optimizers.Adam(0.001))
one_layer_model.fit(X_train_processed, y_train, validation_split=0.2, verbose=0, epochs=100)

2 hidden layers with 100 nodes each

In [ ]:
two_layer_model = keras.Sequential([
    layers.Dense(100, activation='relu'),
    layers.Dense(100, activation='relu'),
    layers.Dense(1)
])
two_layer_model.compile(loss='mean_absolute_error', optimizer=tf.keras.optimizers.Adam(0.001))
two_layer_model.fit(X_train_processed, y_train, validation_split=0.2, verbose=0, epochs=100)

3 hidden layers with 100 nodes each

In [ ]:
three_layer_model = keras.Sequential([
    layers.Dense(100, activation='relu'),
    layers.Dense(100, activation='relu'),
    layers.Dense(100, activation='relu'),
    layers.Dense(1)
])
three_layer_model.compile(loss='mean_absolute_error', optimizer=tf.keras.optimizers.Adam(0.001))
three_layer_model.fit(X_train_processed, y_train, validation_split=0.2, verbose=0, epochs=100)

### Compare Models

In [ ]:
one_layer_model_mae = mean_squared_error(y_test, one_layer_model.predict(X_test_processed))
two_layer_model_mae = mean_squared_error(y_test, two_layer_model.predict(X_test_processed))
three_layer_model_mae = mean_squared_error(y_test, three_layer_model.predict(X_test_processed))